# Travis CI configuration
# based on https://github.com/atom/ci/blob/e7c220a0a74be2303df9901776c1dff1136db885/.travis.yml

language: generic

os:
  - linux
  - osx

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

env:
  matrix:
    - ATOM_CHANNEL=beta
    - ATOM_CHANNEL=stable

branches:
  only:
    - master
    - develop

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
